version: '3.8'

services:
  speaker_verification:
    container_name: speaker_verification
    image: image_speaker_verification
    build: .
    env_file:
      - .env
    networks:
      - ai-hiring_default

networks:
  ai-hiring_default:
    external: true